linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - revive
    - gocritic
    - gofmt

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
