version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - revive
    - gocritic
    - gofmt

settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
